debuggin: true
queue-size: 2
output: ./output
llm: 
  only-ai: true
  seed: 1572738495
  base-url: http://localhost:1234/v1
  token: lm-studio
  model: google/gemma-4-12b-qat
  timeout: 2m
picture:
  min-rating: 5
  count-searches: 0
  ignore: false
