debuggin: false
queue-size: 15
output: ./output
gemini:
  token: Jdjgo803JChpqqzjadpqet0892jvqywnzJPpqyn
ollama:
  host: 127.0.0.1
  port: 8080
  model: gemma
  timeout: 1m
picture:
  min-rating: 5
  count-searches: 2
  ignore: false
