package fetcher

//go:generate mockgen -source content.go -destination mock/content_mock.go

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"strings"

	htgotts "github.com/hegedustibor/htgo-tts"
	"github.com/hegedustibor/htgo-tts/voices"
	"github.com/shredd0r/anki-card-creator/config"
	"github.com/shredd0r/anki-card-creator/extractor"
	"github.com/shredd0r/anki-card-creator/google"
	"github.com/shredd0r/anki-card-creator/llm"
	"github.com/shredd0r/anki-card-creator/models"
	"golang.org/x/sync/errgroup"
)

type CardContent interface {
	GetSubjectType() models.SubjectType
	GetCardContent(ctx context.Context, subject string, usingContext *[]string) (*models.CardContent, error)
	// Method for rating pictures gotten from google image
	GetPicture(ctx context.Context, subject string, usingContext *[]string) (*models.File, error)
	GetPronunciation(subject string) (*models.File, error)
}

// wordCardContent has methods for get volumes for flashcard from Cambridge Dictionary and generated by AI
type wordCardContent struct {
	cfg                 config.PictureConfig
	logger              *slog.Logger
	speech              *htgotts.Speech
	llmProvider         llm.Provider
	cambridgeExtractor  extractor.Cambridge
	googleImageProvider google.Image
}

type phraseCardContent struct {
	logger      *slog.Logger
	llmProvider llm.Provider
}

func NewWordCardContent(cfg config.PictureConfig, logger *slog.Logger, googleImageProvider google.Image, llmProvider llm.Provider, cambridgeExtractor extractor.Cambridge) CardContent {
	return &wordCardContent{
		cfg:                 cfg,
		logger:              logger.WithGroup("word-card-content"),
		speech:              &htgotts.Speech{Language: voices.EnglishUK},
		llmProvider:         llmProvider,
		cambridgeExtractor:  cambridgeExtractor,
		googleImageProvider: googleImageProvider,
	}
}

func (wf *wordCardContent) GetSubjectType() models.SubjectType {
	return models.SubjectTypeWord
}

func (wf *wordCardContent) GetCardContent(ctx context.Context, subject string, usingContext *[]string) (*models.CardContent, error) {
	wf.logger.Debug("start get card content for word")
	errgrp, childCtx := errgroup.WithContext(ctx)

	chanCambridgeCard := make(chan *extractor.CambridgeCard, 1)
	chanGeneratedCard := make(chan *llm.GeneratedCardContent, 1)
	errgrp.Go(func() error {
		cambridgeCard, err := wf.cambridgeExtractor.GetCard(childCtx, subject)
		if err != nil {
			return err
		}
		chanCambridgeCard <- cambridgeCard
		return nil
	})

	errgrp.Go(func() error {
		generatedCardContent, err := wf.llmProvider.GenerateCardContent(childCtx, subject, usingContext)
		if err != nil {
			return err
		}
		chanGeneratedCard <- generatedCardContent
		return nil
	})

	err := errgrp.Wait()
	if err != nil {
		return nil, err
	}

	cambridgeCard := <-chanCambridgeCard
	generatedCardContent := <-chanGeneratedCard

	examples := cambridgeCard.Examples
	if len(examples) == 0 {
		examples = generatedCardContent.Examples
	}

	cardContent := models.CardContent{
		Paraphrase:    cambridgeCard.Explains[0],
		Transcription: cambridgeCard.Transcription,
		Pronunciation: cambridgeCard.Pronunciation,
		Examples:      examples,
		Synonyms:      generatedCardContent.Synonyms,
	}

	return &cardContent, nil
}

func (pf *wordCardContent) GetPicture(ctx context.Context, subject string, usingContext *[]string) (*models.File, error) {
	if true {
		return nil, nil
	}
	var query string
	if usingContext == nil {
		query = subject
	} else {
		query = fmt.Sprintf("%s %s", subject, strings.Join(*usingContext, ", "))
	}

	queryPageProvider, err := pf.googleImageProvider.Request(ctx, query)
	if err != nil {
		return nil, err
	}

	for attempt := range pf.cfg.CountSearches {
		pf.logger.Debug(fmt.Sprintf("attempt: %d for getting picture for subject: %s", attempt, subject))

		picture, err := queryPageProvider.Get(ctx, subject, uint(attempt))
		if err != nil {
			pf.logger.Error("failed get picture for subject", slog.Any("subject", subject), slog.Any("attempt", attempt))
			return nil, err
		}

		rating, err := pf.llmProvider.RatePicture(ctx, subject, picture)
		if err != nil {
			pf.logger.Error("failed rating picture for subject", slog.Any("subject", subject), slog.Any("attempt", attempt))
			return nil, err
		}

		if rating.Rating >= pf.cfg.MinimalRating {
			pf.logger.Debug(fmt.Sprintf("found suitable picture for subject: %s", subject))
			return picture, nil
		}
	}

	pf.logger.Warn(fmt.Sprintf("picture for subject: %s not found, continue without picture", subject))
	return nil, nil
}
func (pf *wordCardContent) GetPronunciation(subject string) (*models.File, error) {
	filename := fmt.Sprintf("%s-prononunciation", subject)
	pronunciation, err := pf.speech.CreateSpeechBuff(subject, filename)
	if err != nil {
		pf.logger.Error("failed generate pronunciation", "err", err.Error())
		return nil, err
	}

	contentBytes, err := io.ReadAll(pronunciation)
	if err != nil {
		pf.logger.Error("failed read pronunciation reader", "err", err.Error())
		return nil, err
	}

	return &models.File{
		Filename: filename,
		Content:  contentBytes,
		MIMEType: "audio/mpeg",
	}, nil
}

func NewPhraseCardContent(logger *slog.Logger, llmProvider llm.Provider) CardContent {
	return &phraseCardContent{
		logger:      logger.WithGroup("phrase-field-component-fetcher"),
		llmProvider: llmProvider,
	}
}

func (pf *phraseCardContent) GetSubjectType() models.SubjectType {
	return models.SubjectTypePhrase
}

func (pf *phraseCardContent) GetCardContent(ctx context.Context, subject string, usingContext *[]string) (*models.CardContent, error) {
	pf.logger.Debug("start get card content for phrase")

	geminiCard, err := pf.llmProvider.GenerateCardContent(ctx, subject, usingContext)
	if err != nil {
		return nil, err
	}

	// For phrase doesn't return transcription and pronunciation
	return &models.CardContent{
		Paraphrase:    geminiCard.Paraphrase,
		Transcription: nil,
		Pronunciation: nil,
		Examples:      geminiCard.Examples,
		Synonyms:      geminiCard.Synonyms,
	}, nil
}

func (pf *phraseCardContent) GetPicture(ctx context.Context, subject string, usingContext *[]string) (*models.File, error) {
	pf.logger.Debug("picture doesnt search for phrase, skip")
	return nil, nil
}
func (pf *phraseCardContent) GetPronunciation(subject string) (*models.File, error) {
	pf.logger.Debug("pronunciation doesnt generate for phrase, skip")
	return nil, nil
}
