package fetcher

//go:generate mockgen -source content.go -destination mock/content_mock.go

import (
	"context"
	"log/slog"

	"github.com/shredd0r/anki-card-creator/extractor"
	"github.com/shredd0r/anki-card-creator/llm"
	"github.com/shredd0r/anki-card-creator/models"
	"golang.org/x/sync/errgroup"
)

type CardContent interface {
	GetSubjectType() models.SubjectType
	GetCardContent(ctx context.Context, subject string, usingContext *[]string) (*models.CardContent, error)
}

// wordCardContentByCambridge has methods for get volumes for flashcard for word gotten from Cambridge dictionary
type wordCardContentByCambridge struct {
	logger             *slog.Logger
	llmProvider        llm.Provider
	cambridgeExtractor extractor.Cambridge
}

// wordCardContentByCambridge has methods for get volumes for flashcard for word generated by llm
// cambridge dictionary used for get pronunciation
type wordCardContentByAI struct {
	logger             *slog.Logger
	llmProvider        llm.Provider
	cambridgeExtractor extractor.Cambridge
}

type phraseCardContent struct {
	logger      *slog.Logger
	llmProvider llm.Provider
}

func NewWordCardContentByCambridge(logger *slog.Logger, llmProvider llm.Provider, cambridgeExtractor extractor.Cambridge) CardContent {
	return &wordCardContentByCambridge{
		logger:             logger.WithGroup("word-card-content-cambridge"),
		llmProvider:        llmProvider,
		cambridgeExtractor: cambridgeExtractor,
	}
}

func (wf *wordCardContentByCambridge) GetSubjectType() models.SubjectType {
	return models.SubjectTypeWord
}

func (wf *wordCardContentByCambridge) GetCardContent(ctx context.Context, subject string, usingContext *[]string) (*models.CardContent, error) {
	wf.logger.Debug("start get card content for word")
	errgrp, childCtx := errgroup.WithContext(ctx)

	chanCambridgeCard := make(chan *extractor.CambridgeCard, 1)
	chanGeneratedCard := make(chan *llm.GeneratedCardContent, 1)
	errgrp.Go(func() error {
		cambridgeCard, err := wf.cambridgeExtractor.GetCard(childCtx, subject)
		if err != nil {
			return err
		}
		chanCambridgeCard <- cambridgeCard
		return nil
	})

	errgrp.Go(func() error {
		generatedCardContent, err := wf.llmProvider.GenerateCardContent(childCtx, subject, usingContext)
		if err != nil {
			return err
		}
		chanGeneratedCard <- generatedCardContent
		return nil
	})

	err := errgrp.Wait()
	if err != nil {
		return nil, err
	}

	cambridgeCard := <-chanCambridgeCard
	generatedCardContent := <-chanGeneratedCard

	examples := cambridgeCard.Examples
	if len(examples) == 0 {
		examples = generatedCardContent.Examples
	}

	cardContent := models.CardContent{
		Paraphrase:    cambridgeCard.Explains[0],
		Transcription: cambridgeCard.Transcription,
		Pronunciation: cambridgeCard.Pronunciation,
		Examples:      examples,
		Synonyms:      generatedCardContent.Synonyms,
	}

	return &cardContent, nil
}

func NewWordCardContentByAI(logger *slog.Logger, llmProvider llm.Provider, cambridgeExtractor extractor.Cambridge) CardContent {
	return &wordCardContentByAI{
		logger:             logger.WithGroup("word-card-content-ai"),
		llmProvider:        llmProvider,
		cambridgeExtractor: cambridgeExtractor,
	}
}

func (wf *wordCardContentByAI) GetSubjectType() models.SubjectType {
	return models.SubjectTypeWord
}

func (wf *wordCardContentByAI) GetCardContent(ctx context.Context, subject string, usingContext *[]string) (*models.CardContent, error) {
	wf.logger.Debug("start get card content for word")

	chanPronunciation := make(chan *models.File, 1)
	chanGeneratedCardContent := make(chan *llm.GeneratedCardContent, 1)
	errgrp, childCtx := errgroup.WithContext(ctx)

	errgrp.Go(func() error {
		pronunciation, err := wf.cambridgeExtractor.GetPronunciation(childCtx, subject)
		if err != nil {
			return err
		}
		chanPronunciation <- pronunciation
		return nil
	})

	errgrp.Go(func() error {
		generatedCardContent, err := wf.llmProvider.GenerateCardContent(childCtx, subject, usingContext)
		if err != nil {
			return err
		}
		chanGeneratedCardContent <- generatedCardContent
		return nil
	})

	if err := errgrp.Wait(); err != nil {
		return nil, err
	}

	pronunciation := <-chanPronunciation
	generatedCardContent := <-chanGeneratedCardContent

	cardContent := models.CardContent{
		Paraphrase:    generatedCardContent.Paraphrase,
		Transcription: generatedCardContent.Transcription,
		Pronunciation: pronunciation,
		Examples:      generatedCardContent.Examples,
		Synonyms:      generatedCardContent.Synonyms,
	}

	return &cardContent, nil
}

func NewPhraseCardContent(logger *slog.Logger, llmProvider llm.Provider) CardContent {
	return &phraseCardContent{
		logger:      logger.WithGroup("phrase-field-component-fetcher"),
		llmProvider: llmProvider,
	}
}

func (pf *phraseCardContent) GetSubjectType() models.SubjectType {
	return models.SubjectTypePhrase
}

func (pf *phraseCardContent) GetCardContent(ctx context.Context, subject string, usingContext *[]string) (*models.CardContent, error) {
	pf.logger.Debug("start get card content for phrase")

	geminiCard, err := pf.llmProvider.GenerateCardContent(ctx, subject, usingContext)
	if err != nil {
		return nil, err
	}

	// For phrase doesn't return transcription and pronunciation
	return &models.CardContent{
		Paraphrase:    geminiCard.Paraphrase,
		Transcription: nil,
		Pronunciation: nil,
		Examples:      geminiCard.Examples,
		Synonyms:      geminiCard.Synonyms,
	}, nil
}
